# Eigen Decomposition in `numpy`
A demonstration of:  
$\textbf{X}v = \lambda v$  
for the first principal eigenvalue of the example in lecture '10 Dimension Reduction'.

In [1]:
import numpy as np

In [2]:
X = np.array([[1, 0.5, 0.333, 0.25],
              [0.5, 1, 0.667, 0.5],
              [0.333, 0.667,1, 0.75],
              [0.25, 0.5, 0.75, 1]
             ])

In [3]:
eVal, eVec = np.linalg.eig(X)

The eigenvalues

In [4]:
eVal

array([2.53622028, 0.84835416, 0.40787166, 0.2075539 ])

The eigenvectors (in columns)

In [5]:
eVec

array([[-0.37772731, -0.81062274, -0.44192197, -0.07012723],
       [-0.53227622, -0.18760462,  0.74150209,  0.36285148],
       [-0.56137693,  0.30107833,  0.04962821, -0.76924952],
       [-0.50878291,  0.46588317, -0.50241086,  0.52122562]])

In [6]:
vec1 = eVec[:,0]
val1 = eVal[0]
val1, vec1

(2.5362202799647053,
 array([-0.37772731, -0.53227622, -0.56137693, -0.50878291]))

The matrix multiplied by the first eigenvalue.

In [7]:
X.dot(vec1)

array([-0.95799966, -1.34996974, -1.42377554, -1.29038555])

The first eigenvalue multiplied by the first eigenvector.

In [8]:
val1 * vec1

array([-0.95799966, -1.34996974, -1.42377554, -1.29038555])